[connections.snowflake]
account = "hyocgxp-kx57838"
user = "SARVESHK76"
password = "Ml762046"
role = "ACCOUNTADMIN"
warehouse = "DEMO_WAREHOUSE"
database = "DEMO"
schema = "PUBLIC"
client_session_keep_alive = true